Update and rename manual.yml to apims.yml

diff --git a/.github/workflows/apims.yml b/.github/workflows/apims.yml
--- a/.github/workflows/apims.yml
+++ b/.github/workflows/apims.yml
@@ -30,7 +30,7 @@ jobs:
 
       - name: Run Python Script
         run: |
-          python ./auto_script.py || { echo "Python script execution failed"; exit 1; }
+          python ./cron_apims.py || { echo "Python script execution failed"; exit 1; }
           
       - name: Git Operations
         run: |
