Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -30,7 +30,7 @@ jobs:
 
       - name: Run Python Script
         run: |
-          python ./data_apims/auto_script.py || { echo "Python script execution failed"; exit 1; }
+          python ./auto_script.py || { echo "Python script execution failed"; exit 1; }
           
       - name: Git Operations
         run: |
