Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -16,30 +16,28 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.9'  # Set the desired Python version
+          python-version: 3.9  # Set the desired Python version
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '20'  # Set the desired Node.js version
+          node-version: 20  # Set the desired Node.js version
 
-      - name: Install Python dependencies
+      - name: Install dependencies
         run: |
           pip install --upgrade pip
-          pip install pandas requests pytz  # Removed datetime as it's part of the standard library
-
-      - name: List files in data_apims directory
-        run: |
-          cd data_apims
-          ls -la  # List files to confirm auto_script.py is present
+          pip install pandas requests pytz
 
       - name: Run Python Script
         run: |
+          python ./data_apims/auto_script.py || { echo "Python script execution failed"; exit 1; }
+          
+      - name: Git Operations
+        run: |
           cd data_apims
-          python auto_script.py || { echo "Python script failed"; exit 1; }
           git config --global user.email "booluckgmie@gmail.com"
           git config --global user.name "booluckgmie"
           git pull
           git add .
           git commit -m "Update data" || echo "No changes to commit"
-          git push --force  # Use the --force flag
+          git push
