Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -1,4 +1,3 @@
-
 name: Scheduled Python Script
 
 on:
@@ -29,14 +28,18 @@ jobs:
           pip install --upgrade pip
           pip install pandas requests pytz  # Removed datetime as it's part of the standard library
 
+      - name: List files in data_apims directory
+        run: |
+          cd data_apims
+          ls -la  # List files to confirm auto_script.py is present
+
       - name: Run Python Script
         run: |
           cd data_apims
-          python auto_script.py
+          python auto_script.py || { echo "Python script failed"; exit 1; }
           git config --global user.email "booluckgmie@gmail.com"
           git config --global user.name "booluckgmie"
           git pull
           git add .
           git commit -m "Update data" || echo "No changes to commit"
-          git push --force  # Use the --force flag to forcefully push changes
-  
+          git push --force  # Use the --force flag
